import {
  TailorProfile,
  Order,
  Offer,
  MeasurementProfile,
  DeliveryJob,
  Review,
} from "@/lib/types";

export const INITIAL_TAILORS: TailorProfile[] = [
  {
    id: "tailor-1",
    userId: "user-tailor-1",
    businessName: "Zari & Resham by Meera",
    tagline: "Heritage Blouses, Bridal Couture & Delicate Zari Craft",
    bio: "Over 18 years mastering bridal cuts, intricate maggam embroidery, and couture designer blouses. Known across Delhi NCR for flawless fitting and exquisite handwork.",
    experienceYears: 18,
    rating: 4.95,
    reviewCount: 342,
    city: "Delhi NCR (South Ex)",
    address: "B-42, Ring Road Market, South Extension Part 1, New Delhi",
    distanceKm: 2.4,
    availability: "AVAILABLE",
    specializations: ["Designer Blouses", "Bridal Lehengas", "Maggam Work", "Silk Sarees"],
    avgStitchingDays: 4,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-101",
        tailorId: "tailor-1",
        category: "BLOUSE",
        name: "Simple Saree Blouse",
        description: "Classic round or square neck, cotton lining included, precision cut.",
        basePrice: 650,
        estimatedDays: 3,
        complexity: "SIMPLE",
        isAvailable: true,
      },
      {
        id: "menu-102",
        tailorId: "tailor-1",
        category: "BLOUSE",
        name: "Designer Cut & Padded Blouse",
        description: "Princess cut, sweetheart/boat neck, concealed zipper, premium padding.",
        basePrice: 950,
        estimatedDays: 4,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-103",
        tailorId: "tailor-1",
        category: "BLOUSE",
        name: "Heavy Bridal & Zari Blouse",
        description: "Intricate hand embroidery framing, latkan doris, double canvas inner lining.",
        basePrice: 1850,
        estimatedDays: 6,
        complexity: "HEAVY_BRIDAL",
        isAvailable: true,
      },
      {
        id: "menu-104",
        tailorId: "tailor-1",
        category: "KURTI",
        name: "A-Line Designer Kurti",
        description: "Straight or A-line silhouette with customized side slits and designer neck.",
        basePrice: 750,
        estimatedDays: 4,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-105",
        tailorId: "tailor-1",
        category: "ALTERATIONS",
        name: "Sleeve & Waist Alteration",
        description: "Slimming waist or adjusting sleeve length with seamless stitching.",
        basePrice: 180,
        estimatedDays: 2,
        complexity: "SIMPLE",
        isAvailable: true,
      },
    ],
    portfolios: [
      {
        id: "port-1",
        tailorId: "tailor-1",
        title: "Royal Crimson Velvet Blouse",
        description: "Cutwork back neck with antique zari wire work for winter bride.",
        garmentCategory: "BLOUSE",
        imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
        tags: ["Velvet", "Bridal", "Zari"],
      },
      {
        id: "port-2",
        tailorId: "tailor-1",
        title: "Raw Silk Banarasi Kurti Set",
        description: "Scalloped neckline with matching cigarette pants.",
        garmentCategory: "KURTI",
        imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
        tags: ["Banarasi", "Festive"],
      },
    ],
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: "off-1",
    code: "AMIYA@100",
    title: "First Order Special Privilege",
    description: "Flat ₹100 off on your first bespoke stitching order",
    discountType: "FIXED_AMOUNT",
    discountValue: 100,
    minOrderValue: 499,
    validUntil: "2026-12-31",
    isActive: true,
  },
  {
    id: "off-2",
    code: "AMIYA@50",
    title: "First Order Welcome Privilege",
    description: "Flat ₹50 off on your first bespoke stitching order",
    discountType: "FIXED_AMOUNT",
    discountValue: 50,
    minOrderValue: 299,
    validUntil: "2026-12-31",
    isActive: true,
  },
  {
    id: "off-3",
    code: "USER@50",
    title: "Exclusive Returning Patron Privilege",
    description: "Flat ₹50 off for returning SILAI patrons",
    discountType: "FIXED_AMOUNT",
    discountValue: 50,
    minOrderValue: 249,
    validUntil: "2026-12-31",
    isActive: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "order-1",
    orderNumber: "SIL-20260928-8421",
    customerId: "cust-1",
    customerName: "Priya Sharma",
    customerPhone: "+91 98112 34567",
    tailorId: "tailor-1",
    tailorName: "Zari & Resham by Meera",
    tailorAddress: "B-42, Ring Road Market, South Extension Part 1, New Delhi",
    garmentName: "Designer Cut & Padded Blouse",
    garmentCategory: "BLOUSE",
    status: "STITCHING",
    stitchingPrice: 950,
    doorstepDeliveryFee: 100,
    discountAmount: 150,
    membershipDiscount: 0,
    taxAmount: 45,
    finalPayableAmount: 945,
    platformCommission: 142.5,
    tailorEarnings: 807.5,
    appliedCoupon: "FIRSTSTITCH",
    pickupAddress: "Flat 402, Royal Palms, Greater Kailash 1, New Delhi",
    deliveryAddress: "Flat 402, Royal Palms, Greater Kailash 1, New Delhi",
    pickupScheduledAt: "2026-09-28T10:00:00Z",
    expectedDeliveryDate: "2026-10-03T18:00:00Z",
    deliveryOtp: "4829",
    measurementType: "SAVED",
    createdAt: "2026-09-28T09:15:00Z",
    updatedAt: "2026-09-29T14:30:00Z",
  },
  {
    id: "order-2",
    orderNumber: "SIL-20260927-1943",
    customerId: "cust-1",
    customerName: "Priya Sharma",
    customerPhone: "+91 98112 34567",
    tailorId: "tailor-1",
    tailorName: "Zari & Resham by Meera",
    tailorAddress: "B-42, Ring Road Market, South Extension Part 1, New Delhi",
    garmentName: "Bespoke Formal Shirt",
    garmentCategory: "SHIRT",
    status: "DELIVERED",
    stitchingPrice: 650,
    doorstepDeliveryFee: 100,
    discountAmount: 0,
    membershipDiscount: 50,
    taxAmount: 35,
    finalPayableAmount: 735,
    platformCommission: 97.5,
    tailorEarnings: 552.5,
    pickupAddress: "Flat 402, Greater Kailash 1, New Delhi",
    deliveryAddress: "Flat 402, Greater Kailash 1, New Delhi",
    expectedDeliveryDate: "2026-09-30T17:00:00Z",
    deliveryOtp: "8192",
    measurementType: "REFERENCE_GARMENT",
    createdAt: "2026-09-25T11:00:00Z",
    updatedAt: "2026-09-30T16:45:00Z",
  },
  {
    id: "order-3",
    orderNumber: "SIL-20260930-9012",
    customerId: "cust-2",
    customerName: "Ananya Deshmukh",
    customerPhone: "+91 98200 87654",
    tailorId: "tailor-1",
    tailorName: "Zari & Resham by Meera",
    tailorAddress: "B-42, Ring Road Market, South Extension Part 1, New Delhi",
    garmentName: "Heavy Bridal & Zari Blouse",
    garmentCategory: "BLOUSE",
    status: "PICKUP_SCHEDULED",
    stitchingPrice: 1850,
    doorstepDeliveryFee: 100,
    discountAmount: 200,
    membershipDiscount: 0,
    taxAmount: 87,
    finalPayableAmount: 1837,
    platformCommission: 277.5,
    tailorEarnings: 1572.5,
    appliedCoupon: "SILAIROYAL",
    pickupAddress: "Tower 3, Apt 1104, DLF Phase 5, Gurugram",
    deliveryAddress: "Tower 3, Apt 1104, DLF Phase 5, Gurugram",
    expectedDeliveryDate: "2026-10-06T18:00:00Z",
    deliveryOtp: "3741",
    measurementType: "DOORSTEP",
    createdAt: "2026-09-30T15:20:00Z",
    updatedAt: "2026-09-30T15:30:00Z",
  },
];

export const INITIAL_DELIVERY_JOBS: DeliveryJob[] = [
  {
    id: "deliv-1",
    orderId: "order-3",
    orderNumber: "SIL-20260930-9012",
    garmentName: "Heavy Bridal & Zari Blouse (Fabric Pickup)",
    type: "CUSTOMER_TO_TAILOR",
    status: "ASSIGNED",
    customerNameMasked: "Ananya D. (+91 98200 ••••)",
    pickupAddressMasked: "DLF Phase 5, Gurugram (Tower 3)",
    tailorName: "Zari & Resham by Meera",
    dropAddressMasked: "South Extension Part 1, New Delhi",
    distanceKm: 8.4,
    payoutAmount: 140,
    deliveryOtpVerified: false,
    createdAt: "2026-09-30T15:30:00Z",
  },
  {
    id: "deliv-2",
    orderId: "order-1",
    orderNumber: "SIL-20260928-8421",
    garmentName: "Designer Blouse Delivery",
    type: "TAILOR_TO_CUSTOMER",
    status: "IN_TRANSIT",
    customerNameMasked: "Priya S. (+91 98112 ••••)",
    pickupAddressMasked: "South Extension Part 1, New Delhi",
    tailorName: "Zari & Resham by Meera",
    dropAddressMasked: "Greater Kailash 1, New Delhi",
    distanceKm: 3.2,
    payoutAmount: 85,
    deliveryOtpVerified: false,
    createdAt: "2026-09-30T14:00:00Z",
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-2",
    customerId: "cust-1",
    customerName: "Priya Sharma",
    tailorId: "tailor-1",
    rating: 5,
    fitRating: 5,
    comment: "Meera ji stitched my bridal silk blouse like absolute poetry! The princess cut hugs flawlessly without any shoulder slippage. Doorstep pickup saved me hours in traffic.",
    createdAt: "2026-09-29T10:00:00Z",
  },
  {
    id: "rev-2",
    orderId: "order-prev-1",
    customerId: "cust-3",
    customerName: "Ritu Singhal",
    tailorId: "tailor-1",
    rating: 5,
    fitRating: 5,
    comment: "Masterji Ahmed's fit is sharper than luxury ready-to-wear shirts. The collar stiffness and button placket are world class.",
    createdAt: "2026-09-26T16:00:00Z",
  },
];

export const INITIAL_MEASUREMENTS: MeasurementProfile[] = [
  {
    id: "meas-1",
    customerId: "cust-1",
    profileName: "My Festive Blouse Fit",
    garmentType: "BLOUSE",
    type: "SAVED",
    isDefault: true,
    measurements: {
      bust: 36,
      underbust: 31,
      waist: 28,
      shoulder: 14.5,
      armhole: 16,
      sleeveLength: 10.5,
      bicep: 12,
      frontNeckDepth: 7,
      backNeckDepth: 9.5,
      blouseLength: 14.5,
      fitStyle: "COMFORT",
      specialNotes: "Prefers deep back neck with dori tie-up and padded cups.",
    },
    createdAt: "2026-09-20T10:00:00Z",
  },
  {
    id: "meas-2",
    customerId: "cust-1",
    profileName: "Casual Straight Kurti",
    garmentType: "KURTI",
    type: "SAVED",
    measurements: {
      chest: 36,
      waist: 30,
      hip: 39,
      shoulder: 14.5,
      kurtiLength: 42,
      sleeveLength: 17,
      slitCut: 19,
      fitStyle: "REGULAR",
    },
    createdAt: "2026-09-22T12:00:00Z",
  },
];
