import {
  TailorProfile,
  Order,
  Offer,
  MeasurementProfile,
  DeliveryJob,
  Review,
} from "@/lib/types";

export const INITIAL_TAILORS: TailorProfile[] = [
  {
    id: "tailor-1",
    userId: "user-tailor-1",
    businessName: "Zari & Resham by Meera",
    tagline: "Heritage Blouses, Bridal Couture & Delicate Zari Craft",
    bio: "Over 18 years mastering bridal cuts, intricate maggam embroidery, and couture designer blouses. Known across Delhi NCR for flawless fitting and exquisite handwork.",
    experienceYears: 18,
    rating: 4.95,
    reviewCount: 342,
    city: "Delhi NCR (South Ex)",
    address: "B-42, Ring Road Market, South Extension Part 1, New Delhi",
    distanceKm: 2.4,
    availability: "AVAILABLE",
    specializations: ["Designer Blouses", "Bridal Lehengas", "Maggam Work", "Silk Sarees"],
    avgStitchingDays: 4,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-101",
        tailorId: "tailor-1",
        category: "BLOUSE",
        name: "Simple Saree Blouse",
        description: "Classic round or square neck, cotton lining included, precision cut.",
        basePrice: 650,
        estimatedDays: 3,
        complexity: "SIMPLE",
        isAvailable: true,
      },
      {
        id: "menu-102",
        tailorId: "tailor-1",
        category: "BLOUSE",
        name: "Designer Cut & Padded Blouse",
        description: "Princess cut, sweetheart/boat neck, concealed zipper, premium padding.",
        basePrice: 950,
        estimatedDays: 4,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-103",
        tailorId: "tailor-1",
        category: "BLOUSE",
        name: "Heavy Bridal & Zari Blouse",
        description: "Intricate hand embroidery framing, latkan doris, double canvas inner lining.",
        basePrice: 1850,
        estimatedDays: 6,
        complexity: "HEAVY_BRIDAL",
        isAvailable: true,
      },
      {
        id: "menu-104",
        tailorId: "tailor-1",
        category: "KURTI",
        name: "A-Line Designer Kurti",
        description: "Straight or A-line silhouette with customized side slits and designer neck.",
        basePrice: 750,
        estimatedDays: 4,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-105",
        tailorId: "tailor-1",
        category: "ALTERATIONS",
        name: "Sleeve & Waist Alteration",
        description: "Slimming waist or adjusting sleeve length with seamless stitching.",
        basePrice: 180,
        estimatedDays: 2,
        complexity: "SIMPLE",
        isAvailable: true,
      },
    ],
    portfolios: [
      {
        id: "port-1",
        tailorId: "tailor-1",
        title: "Royal Crimson Velvet Blouse",
        description: "Cutwork back neck with antique zari wire work for winter bride.",
        garmentCategory: "BLOUSE",
        imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80",
        tags: ["Velvet", "Bridal", "Zari"],
      },
      {
        id: "port-2",
        tailorId: "tailor-1",
        title: "Raw Silk Banarasi Kurti Set",
        description: "Scalloped neckline with matching cigarette pants.",
        garmentCategory: "KURTI",
        imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80",
        tags: ["Banarasi", "Festive"],
      },
    ],
  },
  {
    id: "tailor-2",
    userId: "user-tailor-2",
    businessName: "Masterji Ahmed & Sons",
    tagline: "50 Years of Bespoke Men's & Women's Tailoring Heritage",
    bio: "Third-generation tailoring studio in Old Delhi. Renowned for surgical sharpness in Nehru jackets, custom shirts, formal trousers, and classic anarkalis.",
    experienceYears: 26,
    rating: 4.88,
    reviewCount: 489,
    city: "Delhi NCR (Chandni Chowk)",
    address: "Shop 14, Dariba Kalan, Chandni Chowk, Delhi",
    distanceKm: 3.8,
    availability: "AVAILABLE",
    specializations: ["Men's Shirts & Suits", "Nehru Jackets", "Classic Kurtas", "Salwar Suits"],
    avgStitchingDays: 3,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-201",
        tailorId: "tailor-2",
        category: "SHIRT",
        name: "Bespoke Formal Shirt",
        description: "Fused collar, hand-stitched buttons, french seams, precision sleeve placket.",
        basePrice: 650,
        estimatedDays: 3,
        complexity: "REGULAR",
        isAvailable: true,
      },
      {
        id: "menu-202",
        tailorId: "tailor-2",
        category: "PANTS",
        name: "Custom Tailored Trousers",
        description: "Italian waist curtain, inner grip band, blind-stitched hem, side adjusters.",
        basePrice: 700,
        estimatedDays: 3,
        complexity: "REGULAR",
        isAvailable: true,
      },
      {
        id: "menu-203",
        tailorId: "tailor-2",
        category: "SUIT",
        name: "Royal Bandhgala / Nehru Jacket",
        description: "Canvas chest piece, structured shoulders, satin inner lining, brass buttons.",
        basePrice: 1600,
        estimatedDays: 5,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-204",
        tailorId: "tailor-2",
        category: "KURTI",
        name: "Men's Classic Kurta",
        description: "Mandarin collar, side pockets, clean edge hem.",
        basePrice: 550,
        estimatedDays: 3,
        complexity: "SIMPLE",
        isAvailable: true,
      },
    ],
    portfolios: [
      {
        id: "port-201",
        tailorId: "tailor-2",
        title: "Tussar Silk Nehru Jacket",
        description: "Self-woven gold highlights with antique metal buttons.",
        garmentCategory: "SUIT",
        imageUrl: "https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=80",
        tags: ["Nehru Jacket", "Tussar Silk"],
      },
    ],
  },
  {
    id: "tailor-3",
    userId: "user-tailor-3",
    businessName: "Kala Mandir Boutique",
    tagline: "Contemporary Indo-Western Cuts & Festive Ensembles",
    bio: "Led by NID graduate Sunita Rao. We bring fresh runway sensibilities to everyday ethnic tailoring. Specializing in crop tops, co-ord sets, and modern draped sarees.",
    experienceYears: 12,
    rating: 4.92,
    reviewCount: 215,
    city: "Delhi NCR (Hauz Khas)",
    address: "Village Hauz Khas, Lane 3, New Delhi",
    distanceKm: 4.1,
    availability: "AVAILABLE",
    specializations: ["Indo-Western", "Co-ord Sets", "Corset Blouses", "Anarkali Gowns"],
    avgStitchingDays: 4,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-301",
        tailorId: "tailor-3",
        category: "BLOUSE",
        name: "Contemporary Corset Saree Blouse",
        description: "Boning structure for red-carpet silhouette, tie-up back, built-in cups.",
        basePrice: 1200,
        estimatedDays: 4,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-302",
        tailorId: "tailor-3",
        category: "SUIT",
        name: "Indo-Western 3-Piece Co-ord Set",
        description: "Crop top, palazzo/culotte, and flowy cape/shrug stitching.",
        basePrice: 1450,
        estimatedDays: 5,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-303",
        tailorId: "tailor-3",
        category: "KURTI",
        name: "Flared Peplum Kurti",
        description: "Gathered waist, bishop sleeves, delicate piping finish.",
        basePrice: 850,
        estimatedDays: 3,
        complexity: "REGULAR",
        isAvailable: true,
      },
    ],
    portfolios: [
      {
        id: "port-301",
        tailorId: "tailor-3",
        title: "Champagne Georgette Cape Set",
        description: "Modern asymmetrical hemline with embroidered neck yoke.",
        garmentCategory: "SUIT",
        imageUrl: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80",
        tags: ["Cape", "Modern", "Festive"],
      },
    ],
  },
  {
    id: "tailor-4",
    userId: "user-tailor-4",
    businessName: "Rajputana Silai Ghar",
    tagline: "Authentic Rajasthani Gota Patti, Poshaks & Bridal Lehengas",
    bio: "Specialists in Jaipur gota patti stitching, voluminous kalidar lehengas, and royal Rajputi poshak stitching with authentic dori and hand-tucks.",
    experienceYears: 22,
    rating: 4.97,
    reviewCount: 310,
    city: "Jaipur (Johari Bazaar)",
    address: "Plot 88, Bapu Bazaar Link, Jaipur, Rajasthan",
    distanceKm: 5.6,
    availability: "AVAILABLE",
    specializations: ["Bridal Lehengas", "Gota Patti Work", "Rajputi Poshak", "Anarkali 32-Kali"],
    avgStitchingDays: 7,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-401",
        tailorId: "tailor-4",
        category: "LEHENGA",
        name: "Bridal Kalidar Lehenga & Choli",
        description: "Up to 32 kalis, heavy can-can netting, canvas belt, matching designer choli.",
        basePrice: 2800,
        estimatedDays: 7,
        complexity: "HEAVY_BRIDAL",
        isAvailable: true,
      },
      {
        id: "menu-402",
        tailorId: "tailor-4",
        category: "BLOUSE",
        name: "Gota Patti Embroidered Choli",
        description: "Traditional backless dori design with handmade matching latkans.",
        basePrice: 1100,
        estimatedDays: 4,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-403",
        tailorId: "tailor-4",
        category: "SUIT",
        name: "Floor Length Anarkali Suit",
        description: "Full flare anarkali with inner crepe lining and churidar.",
        basePrice: 1350,
        estimatedDays: 5,
        complexity: "REGULAR",
        isAvailable: true,
      },
    ],
    portfolios: [
      {
        id: "port-401",
        tailorId: "tailor-4",
        title: "Maroon & Gold Royal Rajputi Poshak",
        description: "Authentic marodi embroidery on pure silk.",
        garmentCategory: "LEHENGA",
        imageUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80",
        tags: ["Bridal", "Gota Patti", "Maroon"],
      },
    ],
  },
  {
    id: "tailor-5",
    userId: "user-tailor-5",
    businessName: "Drapes of Bengal (Kolkata Tailors)",
    tagline: "Jamdani Blouses, Bengali Pujo Couture & Tussar Silk Experts",
    bio: "Preserving Bengal's artisanal heritage with high-neck retro blouses, scalloped piping, and cotton daily wear with featherlight feel.",
    experienceYears: 16,
    rating: 4.86,
    reviewCount: 178,
    city: "Kolkata (Gariahat)",
    address: "24/B Rashbehari Avenue, Gariahat, Kolkata",
    distanceKm: 6.2,
    availability: "AVAILABLE",
    specializations: ["Jamdani Blouses", "High-Neck Collars", "Cotton Kurtis", "Saree Fall & Pico"],
    avgStitchingDays: 3,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-501",
        tailorId: "tailor-5",
        category: "BLOUSE",
        name: "Vintage High-Neck Jamdani Blouse",
        description: "Victorian collar or keyhole back with fabric covered buttons.",
        basePrice: 750,
        estimatedDays: 3,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-502",
        tailorId: "tailor-5",
        category: "KURTI",
        name: "Bishnupur Silk Daily Kurti",
        description: "Straight fit with boat neck, tailored for tropical breathability.",
        basePrice: 550,
        estimatedDays: 3,
        complexity: "SIMPLE",
        isAvailable: true,
      },
      {
        id: "menu-503",
        tailorId: "tailor-5",
        category: "ALTERATIONS",
        name: "Saree Fall, Pico & Tassels",
        description: "Precision machine pico edge and pure cotton fall stitching.",
        basePrice: 150,
        estimatedDays: 1,
        complexity: "SIMPLE",
        isAvailable: true,
      },
    ],
    portfolios: [],
  },
  {
    id: "tailor-6",
    userId: "user-tailor-6",
    businessName: "Noor Jahan Bridal Studio",
    tagline: "Lucknowi Chikankari & Zardozi Royal Wedding Finery",
    bio: "Directly connected to master karigars of Hazratganj. We stitch heirloom shararas, ghararas, and bridal dupattas with museum-level stitching.",
    experienceYears: 20,
    rating: 4.98,
    reviewCount: 420,
    city: "Lucknow (Hazratganj)",
    address: "Royal Market, Hazratganj, Lucknow, UP",
    distanceKm: 7.0,
    availability: "BUSY",
    specializations: ["Lucknowi Chikankari", "Bridal Ghararas", "Sharara Sets", "Heavy Dupatta Borders"],
    avgStitchingDays: 6,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-601",
        tailorId: "tailor-6",
        category: "SUIT",
        name: "Traditional Awadhi Gharara Set",
        description: "Pleated knee ruffles (gote), zari border attachment, and short kurti.",
        basePrice: 2200,
        estimatedDays: 6,
        complexity: "HEAVY_BRIDAL",
        isAvailable: true,
      },
      {
        id: "menu-602",
        tailorId: "tailor-6",
        category: "KURTI",
        name: "Pure Georgette Chikankari Kurta",
        description: "Stitching delicate shadow-work fabrics with matching inner slip.",
        basePrice: 850,
        estimatedDays: 4,
        complexity: "REGULAR",
        isAvailable: true,
      },
    ],
    portfolios: [],
  },
  {
    id: "tailor-7",
    userId: "user-tailor-7",
    businessName: "South Star Tailoring (Bengaluru)",
    tagline: "Kanchipuram Silk Saree Blouses & Quick 48-Hour Turnaround",
    bio: "Bengaluru's favorite boutique for corporate women and brides alike. Guaranteed 48-hour delivery option, computerized measurement matching.",
    experienceYears: 14,
    rating: 4.89,
    reviewCount: 275,
    city: "Bengaluru (Indiranagar)",
    address: "100ft Road, 12th Main, Indiranagar, Bengaluru",
    distanceKm: 3.1,
    availability: "AVAILABLE",
    specializations: ["Kanchipuram Blouses", "Express 48h Stitching", "Office Wear Suits", "Alterations"],
    avgStitchingDays: 2,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-701",
        tailorId: "tailor-7",
        category: "BLOUSE",
        name: "Express Kanchipuram Silk Blouse",
        description: "Gold border placement on sleeves and neck, premium lining, ready in 48 hours.",
        basePrice: 1100,
        estimatedDays: 2,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-702",
        tailorId: "tailor-7",
        category: "SUIT",
        name: "Formal Straight Cut Salwar Suit",
        description: "Ideal for daily office elegance with clean French seams.",
        basePrice: 800,
        estimatedDays: 2,
        complexity: "SIMPLE",
        isAvailable: true,
      },
    ],
    portfolios: [],
  },
  {
    id: "tailor-8",
    userId: "user-tailor-8",
    businessName: "Couture Cuts Bandra (Mumbai)",
    tagline: "Celebrity Stylist Tailoring, Bollywood Blouses & Gowns",
    bio: "Trained in Italian pattern drafting. Frequent partner for Bollywood stylists and Bandra fashionistas. Perfect plunge necks, structural corsetry.",
    experienceYears: 15,
    rating: 4.96,
    reviewCount: 380,
    city: "Mumbai (Bandra West)",
    address: "Hill Road, Opp. Elco Arcade, Bandra West, Mumbai",
    distanceKm: 4.5,
    availability: "AVAILABLE",
    specializations: ["Bollywood Blouses", "Evening Gowns", "Modern Lehengas", "Corsetry"],
    avgStitchingDays: 5,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-801",
        tailorId: "tailor-8",
        category: "BLOUSE",
        name: "Infinity / Plunge Neck Bollywood Blouse",
        description: "Red carpet cut with custom cups and invisible shoulder stays.",
        basePrice: 1500,
        estimatedDays: 4,
        complexity: "DESIGNER",
        isAvailable: true,
      },
      {
        id: "menu-802",
        tailorId: "tailor-8",
        category: "LEHENGA",
        name: "Mermaid Cut Saree Skirt / Lehenga",
        description: "Figure-hugging hip fit with cascading flare and side slit.",
        basePrice: 2400,
        estimatedDays: 6,
        complexity: "DESIGNER",
        isAvailable: true,
      },
    ],
    portfolios: [],
  },
  {
    id: "tailor-9",
    userId: "user-tailor-9",
    businessName: "Shree Ganesh Silai Kendra",
    tagline: "Honest Neighborhood Prices & Fast Alterations",
    bio: "Trusted neighborhood tailor serving families for 20 years. Great everyday stitching for school uniforms, cotton kurtis, blouses, and zip repairs.",
    experienceYears: 20,
    rating: 4.75,
    reviewCount: 160,
    city: "Delhi NCR (Lajpat Nagar)",
    address: "Central Market, Lajpat Nagar 2, New Delhi",
    distanceKm: 1.5,
    availability: "AVAILABLE",
    specializations: ["Everyday Kurtis", "Simple Blouses", "Alterations & Resizing", "Pants Fitting"],
    avgStitchingDays: 2,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-901",
        tailorId: "tailor-9",
        category: "BLOUSE",
        name: "Regular Cotton Blouse",
        description: "Front hook, back hook, round neck standard fitting.",
        basePrice: 500,
        estimatedDays: 2,
        complexity: "SIMPLE",
        isAvailable: true,
      },
      {
        id: "menu-902",
        tailorId: "tailor-9",
        category: "KURTI",
        name: "Simple Daily Kurti",
        description: "Comfortable cut for cotton/rayon daily wear.",
        basePrice: 450,
        estimatedDays: 2,
        complexity: "SIMPLE",
        isAvailable: true,
      },
      {
        id: "menu-903",
        tailorId: "tailor-9",
        category: "ALTERATIONS",
        name: "Length Alteration (Jeans / Kurti)",
        description: "Shortening or lengthening hem with original thread color.",
        basePrice: 100,
        estimatedDays: 1,
        complexity: "SIMPLE",
        isAvailable: true,
      },
    ],
    portfolios: [],
  },
  {
    id: "tailor-10",
    userId: "user-tailor-10",
    businessName: "Royal Rajput Gents Tailors",
    tagline: "Fine Bespoke Safas, Achkans, Jodhpuris & Kurta Pajama",
    bio: "Specializing in royal groom and groomsmen ensembles. High armhole cuts, crisp canvas collars, and bespoke hand-pleated dhotis.",
    experienceYears: 19,
    rating: 4.91,
    reviewCount: 240,
    city: "Jaipur (MI Road)",
    address: "MI Road, Near Panch Batti, Jaipur",
    distanceKm: 5.1,
    availability: "NOT_ACCEPTING",
    specializations: ["Jodhpuri Suits", "Groom Achkans", "Kurta Pajama", "Safas"],
    avgStitchingDays: 5,
    isVerified: true,
    commissionRate: 0.15,
    coverImageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80",
    menuItems: [
      {
        id: "menu-1001",
        tailorId: "tailor-10",
        category: "SUIT",
        name: "Bespoke Jodhpuri Suit",
        description: "Classic imperial cut with velvet pocket trim and monogram option.",
        basePrice: 2900,
        estimatedDays: 6,
        complexity: "DESIGNER",
        isAvailable: false,
      },
    ],
    portfolios: [],
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: "off-1",
    code: "FIRSTSTITCH",
    title: "Welcome to SILAI",
    description: "Flat ₹150 off on your first custom stitching order",
    discountType: "FIXED_AMOUNT",
    discountValue: 150,
    minOrderValue: 600,
    validUntil: "2026-12-31",
    isActive: true,
  },
  {
    id: "off-2",
    code: "SILAIROYAL",
    title: "Royal Club Privilege",
    description: "15% off on all designer and bridal stitching orders",
    discountType: "PERCENTAGE",
    discountValue: 15,
    minOrderValue: 1200,
    maxDiscount: 400,
    validUntil: "2026-12-31",
    isActive: true,
  },
  {
    id: "off-3",
    code: "FREESHIP",
    title: "Free Doorstep Pickup & Delivery",
    description: "Complimentary doorstep pickup and drop (₹100 value)",
    discountType: "FIXED_AMOUNT",
    discountValue: 100,
    minOrderValue: 700,
    validUntil: "2026-12-31",
    isActive: true,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "order-1",
    orderNumber: "SIL-20260928-8421",
    customerId: "cust-1",
    customerName: "Priya Sharma",
    customerPhone: "+91 98112 34567",
    tailorId: "tailor-1",
    tailorName: "Zari & Resham by Meera",
    tailorAddress: "B-42, Ring Road Market, South Extension Part 1, New Delhi",
    garmentName: "Designer Cut & Padded Blouse",
    garmentCategory: "BLOUSE",
    status: "STITCHING",
    stitchingPrice: 950,
    doorstepDeliveryFee: 100,
    discountAmount: 150,
    membershipDiscount: 0,
    taxAmount: 45,
    finalPayableAmount: 945,
    platformCommission: 142.5,
    tailorEarnings: 807.5,
    appliedCoupon: "FIRSTSTITCH",
    pickupAddress: "Flat 402, Royal Palms, Greater Kailash 1, New Delhi",
    deliveryAddress: "Flat 402, Royal Palms, Greater Kailash 1, New Delhi",
    pickupScheduledAt: "2026-09-28T10:00:00Z",
    expectedDeliveryDate: "2026-10-03T18:00:00Z",
    deliveryOtp: "4829",
    measurementType: "SAVED",
    createdAt: "2026-09-28T09:15:00Z",
    updatedAt: "2026-09-29T14:30:00Z",
  },
  {
    id: "order-2",
    orderNumber: "SIL-20260927-1943",
    customerId: "cust-1",
    customerName: "Priya Sharma",
    customerPhone: "+91 98112 34567",
    tailorId: "tailor-2",
    tailorName: "Masterji Ahmed & Sons",
    tailorAddress: "Shop 14, Dariba Kalan, Chandni Chowk, Delhi",
    garmentName: "Bespoke Formal Shirt",
    garmentCategory: "SHIRT",
    status: "DELIVERED",
    stitchingPrice: 650,
    doorstepDeliveryFee: 100,
    discountAmount: 0,
    membershipDiscount: 50,
    taxAmount: 35,
    finalPayableAmount: 735,
    platformCommission: 97.5,
    tailorEarnings: 552.5,
    pickupAddress: "Flat 402, Greater Kailash 1, New Delhi",
    deliveryAddress: "Flat 402, Greater Kailash 1, New Delhi",
    expectedDeliveryDate: "2026-09-30T17:00:00Z",
    deliveryOtp: "8192",
    measurementType: "REFERENCE_GARMENT",
    createdAt: "2026-09-25T11:00:00Z",
    updatedAt: "2026-09-30T16:45:00Z",
  },
  {
    id: "order-3",
    orderNumber: "SIL-20260930-9012",
    customerId: "cust-2",
    customerName: "Ananya Deshmukh",
    customerPhone: "+91 98200 87654",
    tailorId: "tailor-1",
    tailorName: "Zari & Resham by Meera",
    tailorAddress: "B-42, Ring Road Market, South Extension Part 1, New Delhi",
    garmentName: "Heavy Bridal & Zari Blouse",
    garmentCategory: "BLOUSE",
    status: "PICKUP_SCHEDULED",
    stitchingPrice: 1850,
    doorstepDeliveryFee: 100,
    discountAmount: 200,
    membershipDiscount: 0,
    taxAmount: 87,
    finalPayableAmount: 1837,
    platformCommission: 277.5,
    tailorEarnings: 1572.5,
    appliedCoupon: "SILAIROYAL",
    pickupAddress: "Tower 3, Apt 1104, DLF Phase 5, Gurugram",
    deliveryAddress: "Tower 3, Apt 1104, DLF Phase 5, Gurugram",
    expectedDeliveryDate: "2026-10-06T18:00:00Z",
    deliveryOtp: "3741",
    measurementType: "DOORSTEP",
    createdAt: "2026-09-30T15:20:00Z",
    updatedAt: "2026-09-30T15:30:00Z",
  },
];

export const INITIAL_DELIVERY_JOBS: DeliveryJob[] = [
  {
    id: "deliv-1",
    orderId: "order-3",
    orderNumber: "SIL-20260930-9012",
    garmentName: "Heavy Bridal & Zari Blouse (Fabric Pickup)",
    type: "CUSTOMER_TO_TAILOR",
    status: "ASSIGNED",
    customerNameMasked: "Ananya D. (+91 98200 ••••)",
    pickupAddressMasked: "DLF Phase 5, Gurugram (Tower 3)",
    tailorName: "Zari & Resham by Meera",
    dropAddressMasked: "South Extension Part 1, New Delhi",
    distanceKm: 8.4,
    payoutAmount: 140,
    deliveryOtpVerified: false,
    createdAt: "2026-09-30T15:30:00Z",
  },
  {
    id: "deliv-2",
    orderId: "order-1",
    orderNumber: "SIL-20260928-8421",
    garmentName: "Designer Blouse Delivery",
    type: "TAILOR_TO_CUSTOMER",
    status: "IN_TRANSIT",
    customerNameMasked: "Priya S. (+91 98112 ••••)",
    pickupAddressMasked: "South Extension Part 1, New Delhi",
    tailorName: "Zari & Resham by Meera",
    dropAddressMasked: "Greater Kailash 1, New Delhi",
    distanceKm: 3.2,
    payoutAmount: 85,
    deliveryOtpVerified: false,
    createdAt: "2026-09-30T14:00:00Z",
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-2",
    customerId: "cust-1",
    customerName: "Priya Sharma",
    tailorId: "tailor-1",
    rating: 5,
    fitRating: 5,
    comment: "Meera ji stitched my bridal silk blouse like absolute poetry! The princess cut hugs flawlessly without any shoulder slippage. Doorstep pickup saved me hours in traffic.",
    createdAt: "2026-09-29T10:00:00Z",
  },
  {
    id: "rev-2",
    orderId: "order-prev-1",
    customerId: "cust-3",
    customerName: "Ritu Singhal",
    tailorId: "tailor-2",
    rating: 5,
    fitRating: 5,
    comment: "Masterji Ahmed's fit is sharper than luxury ready-to-wear shirts. The collar stiffness and button placket are world class.",
    createdAt: "2026-09-26T16:00:00Z",
  },
];

export const INITIAL_MEASUREMENTS: MeasurementProfile[] = [
  {
    id: "meas-1",
    customerId: "cust-1",
    profileName: "My Festive Blouse Fit",
    garmentType: "BLOUSE",
    type: "SAVED",
    isDefault: true,
    measurements: {
      bust: 36,
      underbust: 31,
      waist: 28,
      shoulder: 14.5,
      armhole: 16,
      sleeveLength: 10.5,
      bicep: 12,
      frontNeckDepth: 7,
      backNeckDepth: 9.5,
      blouseLength: 14.5,
      fitStyle: "COMFORT",
      specialNotes: "Prefers deep back neck with dori tie-up and padded cups.",
    },
    createdAt: "2026-09-20T10:00:00Z",
  },
  {
    id: "meas-2",
    customerId: "cust-1",
    profileName: "Casual Straight Kurti",
    garmentType: "KURTI",
    type: "SAVED",
    measurements: {
      chest: 36,
      waist: 30,
      hip: 39,
      shoulder: 14.5,
      kurtiLength: 42,
      sleeveLength: 17,
      slitCut: 19,
      fitStyle: "REGULAR",
    },
    createdAt: "2026-09-22T12:00:00Z",
  },
];
